#### 2024.9.7

**今日学习：
(40)NumPy入门**

In [1]:
import numpy as np

一、NumPy入门-数组

**（1）介绍:**

         全称numerical python，专门针对计算使用，是很多数据或科学相关python包的基础，包括pandas

         其中最核心的数据结构叫 ND array ，意思是n维数组

             如一维数组：[1, 2, 3, 4, 5]；类似python中的列表list，但array数组中的数据类型必须统一，而list则无此要求

                因此效率快是数据处理方面选择NumPy的首要原因；以及NumPy也提供了很多专门做运算的函数

**（2）创建数组:**

       array = np.array([])

In [2]:
array_1 = np.array([1, 2, 3])    # 创建一维数组
array_1                          # 记住jupyter notebook是交互式，返回array_1的值无需print()

array([1, 2, 3])

In [3]:
array_2 = np.array([[1, 2, 3], [4, 5, 6]])    # 创建二维数组，实质是一个嵌套列表，即列表中的每一个元素都是一个列表
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_3 = np.array([1, "warma", True])    # 如果传入的元素数据类型不一致，numpy便会强制将其转换为同一类型
array_3                                   # 在这里便将int和bool数据类型都转换为了str字符串类型

array(['1', 'warma', 'True'], dtype='<U21')

**（3）数组属性:**

        print(array_1.ndim) 
        print(array_1.shape) 
        print(array_1.size)    
        print(array_1.dtype)

In [5]:
print(array_1.ndim)    # .ndim会返回给我们数组的维度
print(array_2.ndim)

1
2


In [6]:
print(array_1.shape)    # .shape会返回一个元组，表示各个维度的元素个数
print(array_2.shape)    # 针对这个二维数组，返回(2, 3)，即表示第一个维度上有两个元素，第二个维度有三个元素（即有两行数据，每行数据三个元素）

(3,)
(2, 3)


In [7]:
print(array_1.size)    # .size会返回给我们数组里元素的总个数
print(array_2.size)    # 针对array_2，一共6个元素

3
6


In [8]:
print(array_1.dtype)    # .dtype会返回给我们数组元素的类型，如int64，其中int表示整数类型，64表示64位比特长度
print(array_2.dtype)

int64
int64


**（4）批量创建数组:**

       array = np.zeros(3)
       array = np.ones(5)
       array = np.arange(0, 6, 2)

In [9]:
np.zeros(3)    # 创建3个元素为0的数组；其中返回的数字都是浮点数

array([0., 0., 0.])

In [10]:
np.ones(5)    # 创建5个元素为1的数组

array([1., 1., 1., 1., 1.])

In [11]:
np.arange(0, 6, 2)    # 类似python中的range()方法，从0开始，到5，步长为2，即针对array的range()方法

array([0, 2, 4])

========================================================

二、NumPy入门-数组练习（无题库）