#### 2024.9.8

**今日学习：
（42）NumPy入门-探索更多数组、（43）小测试、（44）Pandas入门-Series**

In [1]:
import numpy as np

一、NumPy入门-探索更多数组

**（1）拼接一维数组:**

        如果想在一维数组中添加新的元素，可使用np.concatenate([])

        便会将列表中的元素拼接起来

In [2]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_3 = np.zeros(3)

In [3]:
np.concatenate([array_1, array_2])    # concatenate可以接受的参数为列表，即参数为[array_1, array_2]，其中两个array数组为元素（实际上使用括号为元组也可以）

array([1, 2, 3, 4, 5, 6])

In [4]:
combined_1with3 = np.concatenate([array_1, array_3])
combined_1with3                       # 输出的结果都是浮点数，是因为array_1和array_3两者的数据类型不一致，被强制转换了

array([1., 2., 3., 0., 0., 0.])

**（2）数组排序:**

        类似于python中的sorted()和.sort()，前者不改变原始排序，借用此生成一个新的排序；而后者则直接将改变原始排序，不生成新的

        np.sort()就类似与sorted，不改变原始排序

In [31]:
array_4 = np.array([3, 1, 5, 4, 2])
array_4sort = np.sort(array_4)        # 和sorted()一样，不改变原始排序
print(array_4sort)
print(array_4)                        # 保留元素排序

[1 2 3 4 5]
[3 1 5 4 2]


In [30]:
array_5 = np.array([3, 1, 5, 4, 7, 2, 6])
print(array_5.sort())                 # 不生成新的array，什么都不返回，即返回None----但直接改变排序
print(array_5)

None
[1 2 3 4 5 6 7]


**（3）索引获得元素:**

        类似于python中的索引，同样通过[]获取array中的元素

In [7]:
print(array_1[0])
print(array_1[-1])

1
3


In [8]:
array_1[0:2]    # 获取切片，从[0]元素开始，不包括[2]元素----记住切片使用：

array([1, 2])

**（4）数组运算:**

        如形状相同的两个一维数组相加，便会返回一个相同位置元素相加后的数组
        加+、减-、乘*、除/

In [9]:
print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [10]:
array_1 * 2    # 数组和单个数字之间也能执行运算----称之为广播机制，即数字影响array数组中的每一个元素

array([2, 4, 6])

**（5）聚合运算方法:**

        之所以叫聚合操作，是因为它们都是通过一组值来得到一个值

In [11]:
print(array_1.max())
print(array_1.min())
print(array_1.mean())
print(array_1.sum())

3
1
2.0
6


**（6）根据条件筛选数组元素:**

        属于数组和数字之间的操作
        同时也可以结合逻辑符号 & | ~

In [12]:
array_1 > 2             # 结果反应了数组和数字之间操作的结果，只有 3 > 2，因此治只有元素3返回True，此时结果是一个由True和False组成的布尔值数组

array([False, False,  True])

In [13]:
array_1[array_1 > 2]    # 布尔值数组可以用来对形状相同的数组进行索引，[]中布尔值为True的数组会被筛选出来

array([3])

In [14]:
array_1[(array_1 > 1) & (array_1 < 4)]    # 运用逻辑符号 & 表示并且； | 表示或者； ~表示相反

array([2, 3])

======================================================

In [3]:
import pandas as pd

二、Pands入门-Series更强大的数组形态

**（1）介绍:**

        pandas是继承在numpy的基础上，不仅继承了numpy高性能的数组计算功能，还提供了很多复杂精细的数据处理功能

**（2）Series数据结构:**

        Series是pandas的一个数据结构，类似于numpy的一个数组

In [16]:
s1 = pd.Series([1, 3, 5, 7, 9])    # 注意：传入的 Series 的首字母需要大写！
s1                                 # 从输出结果可以看到，与numpy只输出数据结果不同，pandas还输出了元素对应的索引index，以及最后输出数据类型dtype

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [17]:
print(s1.values)    # 使用.values返回数组的元素
print(s1.index)     # 使用.index返回数组的索引----结果：从0开始，到5结束，步长为1；即一共五个数

[1 3 5 7 9]
RangeIndex(start=0, stop=5, step=1)


In [18]:
print(s1[1])       # 返回单个元素
print(s1[1:3])     # 返回切片----返回结果同样是Series格式

3
1    3
2    5
dtype: int64


 **（3）Series的索引:**

        不同于numpy数组的index固定从0开始，Series的索引可以自定义，如从a开始···

In [4]:
s3 = pd.Series([1, 2, 3], index=["a", "b", "c"])    # 这里将索引设定为"a"、"b"、"c"
print(s3)
print(s3["a"])                                      # 此时数字索引仍然可用，为了区分，将默认的数字索引称为“位置索引”，自定义的索引为“标签索引”

a    1
b    2
c    3
dtype: int64
1


In [20]:
s3["a":"c"]    # 不同于位置索引之类的常规索引，切片中的标签索引是包括索引结束元素的！这一点区别需牢记！

a    1
b    2
c    3
dtype: int64

In [21]:
s3[["a", "c"]]    # 也可以在索引的[]中再放入一个["a", "c"]，此时可以通过索引获取任意位置的元素，位置索引也适用

a    1
c    3
dtype: int64

        注意：如果我们自定义标签也为数字时，在使用索引单个元素时，遵循标签索引；但在索引切片时，遵循位置索引
             因此pandas给我们提供了两个更好的索引取值&切片方法：loc和iloc

 **（4）pandas中更好的索引方法:**

        loc：表示用标签索引去取值or切片
        iloc：表示用位置索引去取值or切片

In [22]:
print(s3.loc["a"])
print(s3.iloc[0])

1
1


 **（5）创建Series的另一种方式:**

        给Series这个构造函数直接传入一个字典，字典的键key会自动变成对应的标签索引

In [23]:
s4 = pd.Series({"沃玛":18, "憨色":20, "冷鸟":22})    # 这里的值为18、20、22，对应的标签索引即为"沃玛"、"憨色"、"冷鸟"
s4

沃玛    18
憨色    20
冷鸟    22
dtype: int64

In [24]:
"冷鸟" in s4    # 查看标签是否在 Series中，若返回 True则说明在

True

In [25]:
s4["冷鸟"] = 21    # 更改某个标签对应的值，可以像字典那样通过 array[index] = value 去更新
s4                # 但正如之前所说，如果标签索引也是数字，则难以判断[]中的是标签索引还是位置索引，最好还是使用 s4.loc["冷鸟"] = 20

沃玛    18
憨色    20
冷鸟    21
dtype: int64

**（6）筛选Series元素:**

        正如之前array数组通过布尔组数组筛选出符合条件的值，Series数组也可以
        同时也可以结合逻辑符号 & | ~

In [26]:
s4 > 19    # 返回bool数组

沃玛    False
憨色     True
冷鸟     True
dtype: bool

In [27]:
s4[s4 > 19]    # 通过布尔数组选出对应值

憨色    20
冷鸟    21
dtype: int64

In [28]:
s4[(s4 < 19) | (s4 > 20)]    # 这里使用了逻辑运算符 | 或者 ，其中两个条件都要被()括住，表示条件的优先级高于或运算

沃玛    18
冷鸟    21
dtype: int64